<h2>My Blog</h2>

<p>This Blog is a personal commentary on stories that are related to money laundering prevention and financial crime. The opinions contained in this Blog are my own and in no way necessarily represent the views of anyone else, including those of my employer.</p>

<div>Has the Basel Paper gone too far?</div>

<p>Whilst there is much to commend the now published Basel Committee Paper on "Sound Management of risks related to money laundering and financing of terrorism," there remain a number of concerns that unfortunately the Committee could have but decided not to address, directly in the Paper. The paper reiterates much of what is expected already in particular with respect to financial institutions money laundering prevention programmes. Still in a number of areas the Paper refers to standards expected of Banks, which in my experience are yet to be established as common standards and to achieve compliance with these new standards could be very costly, challenging and burdensome. The one that sticks out is the idea that financial institutions should hold all information about a customer for a firm at the customer level and not at the account level and that all such relevant information including transaction details should be aggregated and made sense of, even if the information is held in different countries, in different legal entities, despite confidentiality and data protection issues and without considering the risks and rewards of any such actions. The Paper now published takes effect formally once individual countries adopt it's contents by amending their own standards, though in practice Banks are on notice that any regulator may adopt the position in any regulatory inspection that Basel standards should be adhered to, especially by Global Financial Institutions. I would have thought greater transparency and understanding about the challenges of addressing new areas and new expectations including providing a transitional period for compliance would have been reasonable.</p>

<p>As at January 2014</p>

<div>Barclays traders' guilt edged mistake!</div>

<p>With the revelations that the day after the LIBOR action against Barclays was announced by the UK FCA, which led soon after to the resignation of CEO Bob Diamond, one bright spark on the Barclays trading floor, Daniel James Plunkett decided to do what some of his LIBOR colleagues had done and put his own and Barclays interests ahead of it's clients. He improperly sought to influence the gold fix on that day so as to avoid paying a legitimate US$3.9 mio to one of it's trading clients. With losses mounting and more to come with more probes into benchmark and other price settings underway in financial institutions, the risks to financial institutions, where once they were focussed on money leaving the bank and not returning (credit risks) and from dealing with customers involved in criminal activity (money laundering risks), the most pressing risk appears to be one or more employees committing unconscionable acts (conduct risks).</p>

<p>As at March 2014</p>

<div>Are Swiss Anti-Bribery Laws to be further strengthened?</div>

<p>Between 2000 and 2006, Switzerland introduced new laws prohibiting corruption, making it a criminal offence to bribe foreign public officials, and making both individuals and in some cases corporates also responsible and capable of prosecution. Still its long overdue that Switzerland took the next step to elevate so called private corruption to a similar level to that of public corruption. Lawmakers in the country have been spurred on by constant allegations of corruption by elements within FIFA, based in Zurich and the new law should be on the books by 2015. Well done Switzerland!</p>

<p>As at March 2015</p>

<div>Is Trade Finance High Risk?</div>

<p>Trade finance is lower risk than other types of financing and assets, according to the Trade Register Report 2014 released by The International Chamber of Commerce (ICC). The risk in question though related mainly to credit risk. Data from the major global commercial banks, reflecting more than 4.5 million transactions with a total exposure of more than US$2.4tn, records that short-term trade finance customer default rates range from a low of 0.033% to a high of 0.241%. This is considerably lower than the default rate for all corporate products, reported as 1.38% by Moody's.</p>

<p>The Report also commented on AML and KYC risks seen as increasing generally. The report stated that, "Enforcement of AML / KYC / KYCC regulations have been tightened in recent years. In addition to significantly enhanced scrutiny, material fines have been imposed on some of the industry's largest players for alleged failings in this area. This has led to a greater focus at many Banks on their customer on boarding and KYC processes, resulting in higher operational costs for the Trade and Export Finance business. Furthermore, resulting increased legal risks have led a number of Banks, especially global players, to review their correspondent banking networks closely, with some of these Banks terminating correspondent banking relationships with perceived outsized risk relating to AML / KYC / KYCC aspects. If this development turns into a broader trend it could potentially have a significant impact on the ability of smaller players to provide international services (such as Trade and Export Finance) for their clients. As a consequence, prudent and efficient operational risk management around AML and KYC issues is becoming increasingly important for 
Banks globally."</p>

<p>Whilst Trade Finance certainly has felt the brunt of increasing regulatory expectations, there remains debate about whether and to what extent Trade Finance is considered "high risk" for money laundering purposes.</p>

<p>For example the Wolfsberg Group (Trade Finance Principles (2011)), "does not however believe that currently there is sufficient evidence to support an assessment of this area as high risk for AML/Sanctions purposes." Whilst to some Trade Finance is seen as complex, to those involved, the products are well established and well understood. Another argument relates to country risks where Trade Finance Products proliferate in regions with some counter parties resident in Countries presenting increased money laundering risks. This argument is a fair one but should not per se elevate Trade Finance to high risk as a product, more to clients in certain countries posing increased risks. Furthermore when a client even from an increased risk country is involved in a Trade Finance transaction, there is more information available about the client and the transaction, including a reasonable overview of the transaction as a whole. For example the issuing bank will have made their customer due diligence, they will have the LC application - outlining the transaction (including counterpart, goods and other details of the transaction). Once the documents are presented the bank will have the full documentation of the transaction; i.e. have the possibility to check against red flags, sanction lists etc. This would not be the case with open account or direct payments, which are commonplace.  Taking the same example on a clean payment, what the bank will see is the party sending the money, the party to receive it as well as the amount. In other words - the bank will not see the underlying transaction, and have very little chance of detecting money laundering, absent a sanction name or other red flag. As such the risk is not increased because there is documentation, but likely the opposite. As a result of increased transparency it is also likely that professional money launderers will want to avoid trade finance products where clean payments are possible. Furthermore it may also be a valid observation to question how suitable trade finance products are for - for example - anti money laundering. The money launderers would need to set up a company - that looks "real" in both ends of the transaction. And more than that they would need to submit and beat the banks customer due diligence process, as well as accept providing linked evidence in case of any future investigation. They would also need to "construct" trade finance transactions that looked real. Whilst no doubt trade finance is like all banking products vulnerable to abuse by money launderers it is not at all clear that trade finance products are the obvious choice and as such care should be taken to describe these products as generically, "high risk.</p>

<p>As at May 2014</p>

<div>Why don't Governments use available Interpol data on stolen passports?</div>

<p>Months after Malaysia Airlines Flight MH370 first went missing over the South China Sea, and after an extensive search of the area and a thorough investigation, the fate of the plane and the passengers remains a mystery. Whilst the most likely explanation remains that the aircraft suffered a major catastrophic event, speculation remains over whether a terrible accident or an intentional act carried out by the pilot, passengers or third parties caused the Plane to vanish.  Until such time as the Plane is located and / or the Planes black box is recovered the events that lead to the disappearance of the plane may never be known. Whilst not considered as the most likely reason for the planes fate, air safety experts have considered whether the airliner could have been the target of a terrorist attack. An early breakthrough in the investigation fuelled this speculation when it was disclosed that at least two people on board were using stolen passports. The passports had been stolen from Italian tourists in Thailand and used by two Iranian passengers to board the plane. Although the men may not have been responsible for the plane crash, the raises the question of how often passports are stolen or forged and what threats this presents to the criminals' purported country of origin.</p>

<p>Interpol says that only three countries in the world screen air passengers against Interpol's database of stolen passports.  Forged passports are a big problem too.  Earlier this month, customs officials in Dubai seized 52 fake passports on the way into the U.A.E. It seems remarkable that with information available it is not being used to screen against at least airline passenger lists, but why stop there and why not extend to wherever governments request identification including passports. If the information was privately available it would surely be expected that Banks would be expected to use it for screening against their customer lists.</p>

<p>As at May 2014</p>

<div>Changes Announced</div>

<p>I was very pleased to see the announcement that I will be joining Standard Chartered Bank as Global Financial Crime Head later in the summer is now public. Whilst having had the privilege to work at UBS for more than 20 years and more importantly gain unique exposure and benefit from numerous truly talented individuals it is also exciting to have a new challenge. I am extremely proud that I have built and lead (in my mind) the best Bank Financial Crime team in the world and that I leave now the leadership of the team in extremely capable 
hands with my deputy John Shih succeeding me and being supported by a strong bench, none better than Trish Sullivan, Mike Bixon, Matt Chapman, Pierre Grumbacher, Rainer Hoerning, Tara Loftus, Jean Marc Futterknecht, Guido Weizenegger, Mark Nelson, Elaine Banar and Elodie Chalmers. John and the team need no additional encouragement from me to maintain the highest standards in financial crime compliance in the years ahead. I would like to express my personal appreciation to a few stand out colleagues, Neil Stocks, Kath Cates, Sally James, Hans Peter Bauer, Andrew Williams and Markus Diethelm for their constant support, unique abilities and dedication to the cause. Thank you!</p>

<p>I look forward to building on the current strengths at SCB and working with the Financial Crime team currently lead by David Howes, who will become my deputy with the aim of making the Financial Crime Team the best and most effective in the industry, on building and maintaining real trust and confidence with all SCB  stakeholders and supporting the business aspirations of the firm. I'm also looking forward to working closely with in particular Tracy Clarke, Board/Court Member, David Fein, General Counsel and Jamie Kelly, the Global Head of Legal & Compliance and his management team, and with their support delivering on our promises.</p>

<p>As at May 2014</p>

<div>What's Luis Suarez chewing next - Marijuana?</div>

<p>Following his World cup disgrace by biting for the third time in his footballing career an opponent in the Uruguay versus Italy match, Suarez finally said sorry, though through typically appropriately clenched teeth. This is thought to be a condition to a transfer to Barcelona from club Liverpool where Suarez excelled, finishing UK Premier Leagues top scorer and voted best player in the League, proving that three bites and you're not out!  Back home in his native Uruguay, Suarez, like his compatriots and those residents of US States; Colorado and Washington after watching a tense but powerful display albeit an exit nevertheless against Belgium, could try to calm down and relax with a puff of marijuana. Both these States and the Country of Uruguay now have the dubious honor of having recently legalized Marijuana. Retailing in Uruguay at about 87  US cents per gram, Suaraz who earns a reported £200,000 per week  is thought more likely to spend his treasure  on expensive anger management therapy whilst at least whist he is in Uruguay it would be legal for him to try a cheaper medicinal alternative.</p>

<p>As at 30 June 2014</p>

<div>How to read and respond to the FATF (identified serious deficiencies) Country lists?</div>

<p>In it's second plenary of the year held on 27 June 2014 in Paris, FATF published it's list of identified jurisdictions that have strategic deficiencies that pose a risk to the international financial system. Whilst Iran and North Korea remain most toxic according to the rankings applied by FATF, four other countries are listed in the next worse category and moreover they have been on this list for quite some time. The countries are: Algeria; Ecuador; Indonesia and Myanmar. Again whilst FATF call on countries to take counter measures against Iran and North Korea, there is no little or no stick used against these 4 countries. In the case of Iran and North Korea many Banks have taken the fact that sanctions are in place from many important countries and that counter measures effectively should deny access by Iranian and North Korean Banks to access to the global financial system but what should a Bank do and how should it therefore react to the continued listing of Algeria; Ecuador; Indonesia and Myanmar on the next worse list. It would be helpful if FATF gave some thought to this and/or indeed member countries in translating FATF concern into action. I expect most Banks include the FATF listings into their country risk ratings which have an impact on correspondent banking risk ratings but is this sufficient? I would recommend that countries be given a limited amount of time to improve, with specific and clear expectations given and that continued deficiencies continuing for 4 reporting periods would also require countermeasures.</p>

<p>As at 30 June 2014</p>

<div>Is ISIS now the richest terrorist group in the World?</div>

<p>In the second largest Bank Robbery in history, the first being the looting of the Iraqi Central Bank in Baghdad at the end of the 2nd Gulf War, the Central Bank in Iraq's 2nd city of Mosul suffered the same fate as the Islamic State of Iraq and Syria (ISIS), an offshoot of Al-Qaeda, stole US$429 mio following it's recent occupation of the city. With all the effort that goes into combatting terrorism finance, is it too much to ask and expect that intelligence agencies and governments ask themselves some very hard questions about how this could possibly have happened and how vulnerable state assets in conflict zones are in supporting terrorist goals and future plans!</p>

<p>As at 1st July 2014</p>

<div>Is the fine for BNP Paribas fair or "economic warfare?"</div>

<p>Having read and digested the publicly available information on the record US$8.9 fine meted out to the largest of France's Banks, I had a couple of observations. Whilst the record fine made the findings, "news," the industry had long been aware that BNP Paribas would become the latest in a long list of European Banks found to have contravened US sanction laws. Moreover other Banks look set to have their dirty laundry washed in public in the months ahead. What was very disconcerting were the revelations, in particular concerning business with Sudan, that business knowingly continued until 2012, even though it pretended to have stopped business in 2007, that it was routed via third party satellite banks via it's Swiss subsidiary and that whilst Compliance officers had raised numerous concerns, the Bank had effectively ignored or more accurately overruled these concerns. Whilst many in the Industry were heading for the exits with respect to business in Sudan, in the case of my former Bank, UBS it was publicly confirmed as one of the earliest, it appears BNP Paribas paid lip service to the risks and reaped commercial rewards as a result. I'm sure the Sudanese were very appreciative of BNP Paribas' accommodation on their behalf. I heard of one Bank, but there were no doubt many, that took a principled stand and when asked by the Sudanese to reconsider exit and to suggest what the Sudanese could do to ensure a speedy reinstatement of business, came the apparent reply..."How about you stop committing genocide in Darfur," to which I'm told the relationship really was at an end.</p>

<p>I keep reading complaints about not just the level of fines levied by US authorities but that these are unjustly targeted at European firms as part of some kind of economic warfare. Whilst I do think there should be a better system for validating the levels of fines and these should be proportionate and subject to independent adjudication, I just don't buy the economic warfare nonsense. This week's Economist magazine reminds it's readers that whilst for money laundering and sanctions fines these have weighed heavily on European firms, of the top 10 fines levied by US authorities against financial institutions, all exceeding US$ 2 bio, only 2 were levied against none US Banks.</p>

<p>As at 4th July 2014</p>
